import upDownArrow from "../../../icons/updownArrow.svg";
export const columns = [
  {
    key: "orderno",
    selectedIcon: upDownArrow,
    name: "Order No",
    alignText: "left",
    width: "200px",
  },
  {
    key: "date",
    selectedIcon: upDownArrow,
    name: "Date",
    alignText: "left",
    width: "200px",
  },
  {
    key: "clientid",
    selectedIcon: upDownArrow,
    name: "Client ID",
    alignText: "left",
    width: "200px",
  },
  {
    key: "clientname",
    selectedIcon: upDownArrow,
    name: "Client Name",
    alignText: "left",
    width: "200px",
  },
  {
    key: "vehicleno",
    selectedIcon: upDownArrow,
    name: "Number",
    alignText: "left",
    width: "200px",
  },
  {
    key: "mark",
    selectedIcon: upDownArrow,
    name: "Mark",
    alignText: "left",
    width: "200px",
  },
  {
    key: "jobtype",
    selectedIcon: upDownArrow,
    name: "Job Type",
    alignText: "left",
    width: "200px",
  },
  {
    key: "labor",
    selectedIcon: upDownArrow,
    name: "Labor",
    alignText: "left",
    width: "200px",
  },
  {
    key: "action",
    selectedIcon: upDownArrow,
    name: "Action",
    alignText: "left",
    width: "200px",
  },
];

export const rows = [
  {
    order_no: "#0032",
    date: "09/03/2021",
    client_id: "#0087",
    name: "Hassan",
    vehicle_name: "LEA 2019",
    make: "Honda",
    job_type: "Wheel",
    price: "3500 RS",
    action: "...",
  },
  {
    order_no: "#0033",
    date: "09/03/2021",
    client_id: "#0087",
    name: "Hassan",
    vehicle_name: "LEA 2019",
    make: "Honda",
    job_type: "Wheel",
    price: "3500 RS",
    action: "...",
  },
  {
    order_no: "#0034",
    date: "09/03/2021",
    client_id: "#0087",
    name: "Hassan",
    vehicle_name: "LEA 2019",
    make: "Honda",
    job_type: "Wheel",
    price: "3500 RS",
    action: "...",
  },
];
